
spring:
 config:
  activate:
   on-profile: "prod"



build:
  version: "1.0"
  
accounts:
  message: "Welcome to Banking App's Accounts Production APIs"
  contactDetails:
    name: "Tina Developer"
    email: "tin@gmail.com"
  onCallSupport: 
   -(353)1900-0123
   -(353)2800-3343