
spring:
 config:
  activate:
   on-profile: "qa"



build:
  version: "2.0"
  
loan:
  message: "Welcome to Banking App's Loans QA APIs"
  contactDetails:
    name: "Eman Developer"
    email: "em@gmail.com"
  onCallSupport: 
   -(353)3900-0123
   -(353)6800-3343