
spring:
 config:
  activate:
   on-profile: "prod"



build:
  version: "1.0"
  
accounts:
  message: "Welcome to Banking App's Card's Production APIs"
  contactDetails:
    name: "Cathrin Developer"
    email: "cat@gmail.com"
  onCallSupport: 
   -(353)1900-0123
   -(353)2800-3343