services:
  accounts:
    image: "ashin54/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8085:9091"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp
  loans:
    image: "ashin54/loans:v1"
    container_name: loans-ms
    ports:
      - "8086:9092"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp
  cards:
    image: "ashin54/cards:v1"
    container_name: cards-ms
    ports:
      - "8087:9093"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp
networks:
  bankapp:
    driver: "bridge"