

        
build:
  version: "3.0"
  
card:
  message: "Welcome to Banking App's Card Local APIs"
  contactDetails:
    name: "Daniel Developer"
    email: "dan@gmail.com"
  onCallSupport: 
   -(353)89000123
   -(353)88003343
