
build:
  version: "3.0"
  
loan:
  message: "Welcome to Banking App's Loan Local APIs"
  contactDetails:
    name: "Mark Developer"
    email: "mk@gmail.com"
  onCallSupport: 
   -(353)89000123
   -(353)88003343

